/**
 * Freezes the current engine's behaviour into conformance/golden.json.
 *
 * This exists because the generator is being ported to Rust, and a port of a
 * *seeded* generator is only correct if it reproduces the original bit for bit.
 * A dungeon that is merely "plausible" is a different dungeon: every map anyone
 * has ever shared as a seed would break.
 *
 * So the contract is pinned here, in the implementation that is currently
 * authoritative, before any of it is rewritten:
 *
 *   1. Raw mulberry32 output for several seeds. The whole port rests on this -
 *      if the PRNG diverges on step 3000, so does everything downstream.
 *   2. The derived helpers (nextInt / shuffle / pick), which is where an
 *      off-by-one in the port would otherwise hide.
 *   3. Whole generated dungeons, reduced to a hash plus enough summary to say
 *      *how* a mismatch differs rather than only that it does.
 *
 * Run: bun run conformance/generate-golden.ts
 */
import { createHash } from "node:crypto";
import { SeededRandom } from "../src/lib/random.ts";
import { generateDungeon } from "../src/engine/generate.ts";
import { DEFAULT_CONFIG } from "../src/ai/schema.ts";
import type { DungeonConfig } from "../src/ai/schema.ts";
import type { Dungeon } from "../src/engine/types.ts";

const SEEDS = [0, 1, 42, 1337, 2 ** 31 - 1, -1, 123456789];

/** Doubles are compared exactly; 17 significant digits round-trips an f64. */
const f = (n: number) => n.toPrecision(17);

function rngVectors() {
  return SEEDS.map((seed) => {
    const r = new SeededRandom(seed);
    const first = Array.from({ length: 16 }, () => f(r.next()));

    // Advance far enough that a wrong integer width shows up.
    const r2 = new SeededRandom(seed);
    for (let i = 0; i < 10_000; i++) r2.next();
    const at10k = f(r2.next());

    const r3 = new SeededRandom(seed);
    return {
      seed,
      first16: first,
      at10k,
      nextInt_0_99: Array.from({ length: 8 }, () => r3.nextInt(0, 99)),
      nextInt_neg: Array.from({ length: 4 }, () => r3.nextInt(-50, 50)),
      nextFloat: Array.from({ length: 4 }, () => f(r3.nextFloat(-1.5, 2.5))),
      shuffle16: r3.shuffle([...Array(16).keys()]),
      picks: Array.from({ length: 6 }, () => r3.pick(["a", "b", "c", "d", "e"])),
      chances: Array.from({ length: 8 }, () => r3.chance(0.5)),
    };
  });
}

/** Canonical, order-independent reduction of a dungeon. */
function summarise(d: Dungeon) {
  const cells: number[] = [];
  const counts: Record<number, number> = {};
  for (const row of d.grid) {
    for (const c of row) {
      cells.push(c.type);
      counts[c.type] = (counts[c.type] ?? 0) + 1;
    }
  }

  const rooms = d.rooms
    .map((r) => `${r.id}:${r.x},${r.y},${r.width},${r.height}:${r.shape ?? ""}:${r.role ?? ""}`)
    .sort();

  const h = createHash("sha256");
  h.update(cells.join(","));
  h.update("|");
  h.update(rooms.join("|"));

  return {
    gridHash: h.digest("hex").slice(0, 32),
    width: d.grid[0]?.length ?? 0,
    height: d.grid.length,
    roomCount: d.rooms.length,
    cellTypeCounts: counts,
    firstRooms: rooms.slice(0, 5),
  };
}

const CASES: Array<{ name: string; config: DungeonConfig }> = [
  { name: "default", config: { ...DEFAULT_CONFIG, seed: 12345 } },
  {
    name: "constructed-dense-small",
    config: { ...DEFAULT_CONFIG, seed: 7, layout_style: "constructed",
              room_density: "Dense", room_size: "Small", corridors: "Straight" },
  },
  {
    name: "organic-sparse-huge",
    config: { ...DEFAULT_CONFIG, seed: 99, layout_style: "organic",
              room_density: "Sparse", room_size: "Huge", corridors: "Labyrinth",
              corridor_complexity: 0.9 },
  },
  {
    name: "symmetry-four-way",
    config: { ...DEFAULT_CONFIG, seed: 2024, symmetry: "Four-Way",
              dead_ends: "Many", stairs: "Many" },
  },
];

function dungeonVectors() {
  return CASES.map(({ name, config }) => {
    // Generated twice: a generator that is not reproducible within one process
    // is not going to be reproducible across languages either.
    const a = summarise(generateDungeon(config));
    const b = summarise(generateDungeon(config));
    if (a.gridHash !== b.gridHash) {
      throw new Error(`"${name}" is not deterministic in TypeScript - the port cannot be specified against it`);
    }
    return { name, config, ...a };
  });
}

const golden = {
  note: "Generated by conformance/generate-golden.ts. The Rust port must reproduce every value here exactly.",
  generatedFrom: "typescript",
  rng: rngVectors(),
  dungeons: dungeonVectors(),
};

const out = new URL("./golden.json", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
await Bun.write(out, JSON.stringify(golden, null, 2) + "\n");
console.log(`wrote ${out}`);
console.log(`  ${golden.rng.length} rng vectors, ${golden.dungeons.length} dungeon vectors`);
for (const d of golden.dungeons) {
  console.log(`  ${d.name.padEnd(26)} ${d.width}x${d.height} rooms=${String(d.roomCount).padStart(3)} ${d.gridHash}`);
}
